.gitignore
CHANGELOG.md
README.md
docker-compose.override.yml.example
docker-compose.yml
docker/Dockerfile
src/index.js

Added docker integration.
```sh
$ cd share-mrdemonwolf-me
$ cp docker-compose.overrride.yml.example docker-compose.override.yml
$ docker-compose up -d --build
```
Replace values in `docker-compose.override.yml` with your own found at [pm2+](https://app.pm2.io)

Docker integration

---

src/controllers/admin.js
src/controllers/gallery.js
src/controllers/owner.js
src/index.js
src/middleware/roleCheck/isOwner.js
src/models/Upload.js
src/routes/admin.js
src/routes/gallery.js
src/views/admin/gallery.ejs
src/views/gallery/index.ejs
src/views/partials/admin/navbar.ejs
src/views/partials/navbarUser.ejs
src/views/partials/userRoles.ejs
test/1-auth.spec.js

Even a owner middleware with one time token gen.
- Creates a onetime token in console.
- One the token is vaild it will convert **one** user to owner.

Added owner support to basic functions.

---

docker-compose.yml
src/controllers/auth.js
src/models/User.js
src/views/partials/account/basicInfo.ejs
src/views/partials/admin/users/edit/roles.ejs

- Added IP location information to account details.

Now displays last login location and a link to check the IP.

---

.env.example
src/controllers/tokens.js
src/index.js
src/views/partials/footer.ejs

Issue Number: [feature_footer](https://trello.com/c/QEcqRzGH)
- Updated footer to use the new env.

Feature footer

---

docs/_config.yml
docs/index.md
src/controllers/account.js
src/controllers/admin.js
src/index.js
src/middleware/admin/deleteUser.js
src/middleware/admin/putBan.js
src/middleware/admin/putEditUser.js
src/middleware/admin/putSuspend.js
src/middleware/api/isTokenVaild.js
src/views/admin/users/edit.ejs
src/views/partials/admin/usersList.ejs

Issue Number: [cleanup-code](https://trello.com/c/gmCSRbgD)
- Delete user
- and more

Cleanup code

---

bower.json

Issue Number: [bug_bower](https://trello.com/c/KHExpwj7)
- Saved the frameworks with bower to the json.

Fixed the bower json file by saving the depends.

---

docs/docs/api/api.md
docs/docs/api/v1.md
docs/docs/configuration/configuration.md
docs/docs/configuration/sendgrid.md
docs/docs/sendgrid.md
docs/docs/uploaders/sharex.md
docs/docs/uploaders/uploaders.md
docs/index.md
src/public/sw.js

Issue Number:  [feature_docs](https://trello.com/c/BN0X8rCF)
- Updated docs with sharex infomation
- Added sendgrid.

Feautre docs

---

src/views/partials/account/account.ejs
src/views/partials/account/toggles.ejs

Issue Number: [101](https://trello.com/c/hjT02fxp)
- Re renders the email label when streamer is enabled and disabled.

Streamer mode enabled on the account page updates the email label.

---

src/controllers/admin.js
src/index.js
src/models/Settings.js
src/public/sw.js
src/routes/admin.js
src/validation/admin/transferOwnership.js
src/views/admin/index.ejs
src/views/admin/settings/index.ejs
src/views/partials/admin/navbar.ejs

Issue Number: [100](https://trello.com/c/IGD0y8fb)
- Owners can move ownership to another user.

Feature transfer ownership

---

src/views/admin/index.ejs

Issue Number: [110](https://trello.com/c/S6vt95rr)
- Fixed text

Fixed text in the dashboard card link.

---

docs/docs/changelog.md

Issue Number: [111](https://trello.com/c/i6wSeG5l)
- Updated changelog

Added changes to changelog.

---

docs/docs/changelog.md

Issue Number: [115](https://trello.com/c/c2TslgZt)
- Fixed typos

Fixed typos in docs.

---

src/public/sw.js

Issue Number: [113](https://trello.com/c/SZmr3Uor)

Fixed the bug.

---

docs/index.md

Issue Number: [116](https://trello.com/c/RWRajlCn)

Fixed linking in readme and docs to the new repo name.

---

README.md
src/views/admin/users/view.ejs
src/views/partials/admin/users/edit/status.ejs
src/views/partials/admin/users/view/status.ejs

Issue Number: [117](https://trello.com/c/BSJZCDLZ)
- Displays ban and temp ban in view and edit.

Feature admin users

---

test/3-user.spec.js

Issue Number: [106](https://trello.com/c/WDbWlZed)
- Tests for MFA both for creaing and verifty

Added mfa test.

---

docs/index.md

Issue Number: [120](https://trello.com/c/6241OEmL)

Fixed small typo.

---

.eslintrc
src/controllers/admin.js
src/controllers/auth.js
src/emails/AdminCreateUser.js
src/emails/AdminCreateUserActivation.js
src/index.js
src/models/User.js
src/routes/admin.js
src/validation/admin/newUser.js
src/views/admin/users/new.ejs
src/views/partials/admin/users/new/account.ejs
src/views/partials/admin/users/new/roles.ejs
src/views/partials/admin/users/new/toggles.ejs
src/views/partials/admin/usersList.ejs

Issue Number: [114](https://trello.com/c/fhPeVzsa)
- Can now add users in admin panel

Feature admin create user

---

src/index.js
src/middleware/isSignupsDisabled.js

Issue Number: [132](https://trello.com/c/hdtylwu7)
- Checks if signups are disabled before user can post to the signup.

Fixed bug which still allowed users to signup even when it's disabled.

---

ecosystem.config.js

Issue Number: [147](https://trello.com/c/y7lOok86)

Fixed the pm2 ecosystem file.

---

docs/docs/changelog.md

Issue Number: [134](https://trello.com/c/7QS6jzjJ)
- Added 4.0.1 to the changelog

Updated the changelog.

---

README.md

Read me update.
Issue Number: [141](https://trello.com/c/MRN87X1E)
- Added cli tool to the readme.

Updated readme to include the new cli tool.

---

src/index.js

Issue Number: [131](https://trello.com/c/Jz4H8dfO)
- On production it does not show dev on the version.
- Moved the dev tag closer to the version number.

Fixed displaying dev on the version even when it was in production.

---

.env.example
docs/docs/configuration/configuration.md

Issue Number: [163](https://trello.com/c/JUeiKTBX)
- Added the UPLOAD_LIMIT to the example.
- Added the UPLOAD_LIMIT to the docs.

Fixed the missing env param in the example and docs for upload limit.

---

src/middleware/api/fileCheck.js
src/middleware/isSignupsDisabled.js

Issue Number: [164](https://trello.com/c/u2YpVEJR)
- Fixed signup middleware
- Fixed filecheck middlewar

Fixed issues with the true/false process.envs in the signup etc.

---

src/index.js
src/views/auth/login.ejs
src/views/user/forgot-password.ejs
src/views/user/resend-activation.ejs

Issue Number: [133](https://trello.com/c/aLTgMWye)
- Disable showing of signup on pages.

Added signup check for pages.  To disable them from showing.

---

src/index.js
src/middleware/isOwner.js

Issue Number: [140](https://trello.com/c/kH9mrxRu)
- Disable the /owner route

Added a way to disable the owner route.

---

docs/_config.yml
docs/docs/changelog.md
docs/docs/configuration/configuration.md

Issue Number: [134](https://trello.com/c/7QS6jzjJ)
- Updated changelog for next version
- Added new env for config page

Updated changelog and added the new env.

---

package.json
test/3-user.spec.js

Issue Number: [124](https://trello.com/c/sI9jKO9e)

Removed console.log()

---

package-lock.json
package.json
src/controllers/account.js
src/index.js
src/limiters/account.js
src/routes/account.js
src/views/account/index.ejs
src/views/partials/account/basicInfo.ejs
src/views/partials/account/mfa.ejs

Issue Number: [155](https://trello.com/c/nR28BBrK)
- Added mini api
- Added click event for the loading of the data
- Added rate limit for this.

Feature user per space used

---

src/index.js
src/middleware/account/isOwner.js

Issue Number: [172](https://trello.com/c/wbNw2pnE)
- Shows error if the owner tries to delete there account.

Fixed bug where the owner could delete them selfs on the account page

---

src/controllers/admin.js
src/index.js
src/limiters/admin.js
src/views/admin/index.ejs

Issue Number: [150](https://trello.com/c/r4iXKD7D)

Feature add total space used

---

package-lock.json
package.json
src/controllers/config.js
src/validation/api/v1/delete.js
src/validation/config.js
src/views/config/index.ejs

Issue Number: [157](https://trello.com/c/3e6fr4Se)

Added share-cli support for the config gen.

---

src/controllers/admin.js
src/controllers/auth.js
src/controllers/config.js
src/controllers/user.js
src/validation/config.js

Fixed config vaildation as it did not return next.
Issue Number: [184](https://trello.com/c/k6uGtFrC)

Bug replace the tokens in emails

---

src/validation/signup.js

Issue Number: [180](https://trello.com/c/4fprMpUl)

Fixed the check now it should check username or email.

---

docs/docs/changelog.md

Issue Number: [185](https://trello.com/c/Hg7dc3ST)

Updated changelog.

---

docs/docs/api/v2.md
src/controllers/admin.js
src/controllers/api/v1/upload.js
src/controllers/api/v2/link.js
src/controllers/api/v2/upload.js
src/controllers/index.js
src/controllers/links.js
src/index.js
src/models/Upload.js
src/views/partials/account/uploads/uploadsList.ejs
src/views/partials/admin/users/edit/toggles.ejs

Issue Number: [178](https://trello.com/c/EFftMFXh)

Feature upload file name

---

src/controllers/admin.js
src/controllers/api/v2/upload.js
src/controllers/index.js
src/index.js
src/routes/index.js
src/routes/view.js
src/views/partials/account/uploads/uploadsList.ejs
src/views/partials/admin/uploadsList.ejs
src/views/partials/view/image/header.ejs
src/views/view/image.ejs

Issue Number: [194](https://trello.com/c/mhrr5iDr)

Feature view page

---

src/controllers/api/v2/link.js
src/views/partials/account/links/linksList.ejs

Issue Number: [193](https://trello.com/c/CbpJSf4b)

Tags now work again.

---

src/controllers/admin.js
src/controllers/links.js
src/index.js
src/models/Link.js
src/routes/admin.js
src/routes/links.js
src/views/admin/links.ejs
src/views/admin/uploads.ejs
src/views/partials/admin/linksList.ejs
src/views/partials/admin/navbar.ejs
src/views/partials/admin/uploadsList.ejs

Issue Number: [196](https://trello.com/c/A31jtoEL)

Feature admin links

---

src/index.js
src/validation/accountUpdate.js
src/validation/admin/newUser.js
src/validation/admin/suspendUser.js
src/validation/admin/transferOwnership.js
src/validation/admin/uploadLogo.js
src/validation/admin/userUpdate.js
src/validation/api/v2/link.js
src/validation/config.js
src/validation/forgot-password.js
src/validation/linkCreate.js
src/validation/linkUpdate.js
src/validation/login.js
src/validation/resend-activation.js
src/validation/reset-password.js
src/validation/signup.js
src/validation/tokens/create-token.js
src/validation/tokens/rename-token.js
src/validation/uploadUpdate.js

Feature add link validation

---

package-lock.json
package.json
src/controllers/account.js
src/controllers/admin.js
src/controllers/links.js
src/index.js
src/routes/admin.js
src/routes/api/v2/delete.js
src/validation/linkCreate.js
src/views/account/index.ejs
src/views/links/index.ejs
src/views/partials/account/basicInfo.ejs

Issue Number: [186](https://trello.com/c/byJWR9Pp)

Feature export data

---

src/controllers/account.js
src/views/partials/account/uploads/uploadsList.ejs

And fixed the order of the table in uploadlist.
Issue Number: [197](https://trello.com/c/Vj81dMHJ)

Added links to be deleted whhen account is removed

---

docs/docs/changelog.md
docs/index.md

Feature changelog

---

docs/docs/changelog.md
docs/docs/configuration/configuration.md

Issue Number: [203](https://trello.com/c/e9Y4ZVsZ)

Docs update

---

src/middleware/api/isBannedDelete.js
src/routes/api/v1/delete.js
src/routes/api/v2/delete.js

Issue Number: [180](https://trello.com/c/L1Sei1B0)

Added api check for if they are banned.

---

src/views/partials/account/uploads/uploadsList.ejs

Issue Number: [207](https://trello.com/c/FDgTdsBQ)
-
-
-

Fixed the bug.:

---

client/components/Login/Basic.vue
client/components/Login/TwoFactor.vue
client/middleware/alreadyAuthenticated.js
client/nuxt.config.js
client/pages/index.vue
client/pages/login/index.vue
client/store/login.js
package-lock.json
package.json

Issue Number: [SHAER-29](https://mrdemonwolf.atlassian.net/browse/SHARE-29)
- Added basic login page.
- Re Enabled the middleware for alreadyAuth

[SHARE-29] Implement Login Page

---

client/assets/vectors/heroicon/outline/menu-alt-2.svg
client/components/Account/DesktopSidebar.vue
client/components/Account/MobileSidebar.vue
client/components/Account/Modal/DisableTwoFactor.vue
client/components/Account/Modal/EnableTwoFactor.vue
client/components/Account/Modal/RevokeAllDevices.vue
client/components/Shared/ProfileDropdown.vue
client/layouts/account.vue
client/nuxt.config.js
client/package-lock.json
client/package.json
client/pages/account/devices/index.vue
client/pages/account/email-change/_token/index.vue
client/pages/account/index.vue
client/pages/account/personal-information/index.vue
client/pages/account/security/index.vue
client/plugins/filters.js
client/plugins/is-empty.js
client/plugins/js-sha512.js
client/plugins/vue-click-outside.js
client/store/account.js

Issue Number: [SHARE-28](https://mrdemonwolf.atlassian.net/browse/SHARE-28)
- Added basics of the account pages.

[SHARE-28] Implement Account Page

---

vetur.config.js

Issue Number: [SHARE-37](https://mrdemonwolf.atlassian.net/browse/SHARE-37)
- Fix's the VS Code Vue tools by creating the config.

[SHARE-37] Implement vetur config in root

---

.gitignore
server/models/Uploads.js

Issue Number: [SHARE-49](https://mrdemonwolf.atlassian.net/browse/SHARE-49)
-
-
-

[SHARE-49] Create Upload Model

---

.gitignore
server/index.js
server/package-lock.json
server/package.json
server/routes/3rd-party/upload.js
server/routes/upload.js

Issue Number: [SHARE-7](https://mrdemonwolf.atlassian.net/browse/SHARE-7)
-
-
-

[SHARE-7] Implement /3rd-party/upload endpoint

---

server/models/APIKey.js

Issue Number: [SHARE-53](https://mrdemonwolf.atlassian.net/browse/SHARE-53)

[SHARE-53] Create APIKey Model

---

server/index.js
server/routes/apiKey.js

Issue Number: [SHARE-54](https://mrdemonwolf.atlassian.net/browse/SHARE-54)
-
-
-

[SHARE-54] Implement /apikey endpoint

---

server/routes/apiKey.js

Issue Number: [SHARE-55](https://mrdemonwolf.atlassian.net/browse/SHARE-55)

[SHARE-55] Implement /apikey endpoint

---

server/routes/apiKey.js

Issue Number: [SHARE-56](https://mrdemonwolf.atlassian.net/browse/SHARE-56)

[SHARE-56] Implement /apikey/:apikey_id endpoint

---

server/routes/apiKey.js

Issue Number: [SHARE-58](https://mrdemonwolf.atlassian.net/browse/SHARE-58)
-
-
-

[SHARE-58] Implement /apikey/:apikey_id endpoint

---

server/routes/apiKey.js

Issue Number: [SHARE-57](https://mrdemonwolf.atlassian.net/browse/SHARE-57)
-
-
-

[SAHRE-57] Implement /apikey/:apikey_id endpoint

---

server/middleware/isAPIKeyValid.js
server/routes/3rd-party/upload.js

Issue Number: [SHARE-64](https://mrdemonwolf.atlassian.net/browse/SHARE-64)
-
-
-

[SHARE-64] Added APIKey middleware to the 3rd-party routes.

---

docs/content/en/api-account.md
docs/content/en/api-apikey.md
docs/content/en/api.md
docs/content/en/sendgrid.md
server/routes/apiKey.js

Issue Number: [SHARE-51](https://mrdemonwolf.atlassian.net/browse/SHARE-51)
-
-
-

[SHARE-51] Implement /apikey docs

---

client/.env.example
client/nuxt.config.js

Issue Number: [SHARE-81](https://mrdemonwolf.atlassian.net/browse/SHARE-81)

[SHARE-81] Update .env and where it's used.

---

server/index.js
server/routes/stats.js

Issue Number: [SHARE-42](https://mrdemonwolf.atlassian.net/browse/SHARE-42)
-
-
-

[SHARE-42] Implement /stats endpoint

---

client/components/Shared/StatsCard.vue
client/nuxt.config.js
client/package-lock.json
client/package.json
client/pages/dashboard/index.vue
client/plugins/vue-content-loader.js
server/routes/stats.js

Issue Number: [SHARE-82](https://mrdemonwolf.atlassian.net/browse/SHARE-82)

[SHARE-82] Integrate /stats into dashboard

---

server/middleware/auth/isRefreshTokenValid.js
server/middleware/auth/isRegistration.js
server/middleware/auth/isSessionValid.js
server/middleware/isAPIKeyValid.js
server/middleware/isAccountActivated.js
server/routes/3rd-party/upload.js
server/routes/account.js
server/routes/apiKey.js
server/routes/auth.js
server/routes/stats.js
server/routes/upload.js
server/routes/user.js

Issue Number: [SHARE-62](https://mrdemonwolf.atlassian.net/browse/SHARE-62)
-
-
-

[SHARE-62] Implement /upload endpoint

---

server/routes/account.js

Issue Number: [SHARE-71](https://mrdemonwolf.atlassian.net/browse/SHARE-71)

[SHARE-71] Update  /account/two-factor endpoint

---

client/store/account.js

Issue Number: [SHARE-83](https://mrdemonwolf.atlassian.net/browse/SHARE-83)
-
-
-

[SHARE-83] Update Account Security Page

---

docs/content/en/api-account.md

Issue Number: [SHARE-72](https://mrdemonwolf.atlassian.net/browse/SHARE-72)
-
-
-

[SHARE-72] Update  /account/two-factor docs

---

client/layouts/default.vue
client/pages/index.vue
client/tailwind.config.js

Issue Number: [SHARE-88](https://mrdemonwolf.atlassian.net/browse/SHARE-88)
-

[SHARE-88] Landing Page showing wrong BG on dark-mode

---

server/routes/3rd-party/upload.js
server/routes/auth.js

Issue Number: [SHARE-89](https://mrdemonwolf.atlassian.net/browse/SHARE-89)
-
-
-

[SHARE-89] Update /3rd-party/upload endpoint

---

server/models/Upload.js
server/routes/3rd-party/upload.js
server/routes/upload.js

Issue Number: [SHARE-79](https://mrdemonwolf.atlassian.net/browse/SHARE-79)
-

[SHARE-79] Implement /uploads/:upload_id/raw

---

client/nuxt.config.js
client/package-lock.json
client/package.json
client/server-middleware/u.js

Issue Number: [SHARE-80]
-
-
-
[SHARE-80]: https://mrdemonwolf.atlassian.net/browse/SHARE-80

[SHARE-80] Implement /u/raw/:upload_id / /u/raw/:upload_id.ext

---

server/models/Upload.js
server/routes/upload.js

Issue Number: [SHARE-91](https://mrdemonwolf.atlassian.net/browse/SHARE-91)
-
-
-

[SHARE-91] Implement /uploads/:upload_id Endpoint

---

docs/content/en/installation.md

Fixed share link

---

client/pages/account/devices/index.vue
server/routes/account.js
server/routes/upload.js

Issue Number: [SHARE-95](https://mrdemonwolf.atlassian.net/browse/SHARE-95)
-

 [SHARE-95] Update error codes.

---

server/routes/account.js
server/routes/auth.js
server/routes/upload.js
server/routes/user.js
server/validation/upload/updateUpload.js

Issue Number: [SHARE-63](https://mrdemonwolf.atlassian.net/browse/SHARE-63)
-
-
-

[SHARE-63] Implement /upload/:upload_id endpoint.

---

server/routes/upload.js

[SHARE-61] Implement /upload/:upload_id endpoint

---

server/routes/3rd-party/upload.js
server/routes/upload.js

[SHARE-97] Update /3rd-party/upload endpoint

---

server/models/Queue.js

Issue Number: [SHARE-99](https://mrdemonwolf.atlassian.net/browse/SHARE-99)
-
-
-

[SHARE-99] Implement Queue Model.

---

server/models/Queue.js
server/routes/upload.js

Issue Number: [SHARE-98](https://mrdemonwolf.atlassian.net/browse/SHARE-98)
-
-
-

[SHARE-98] Implement /upload endpoint.

---

.gitignore
src/views/admin/gallery.ejs
src/views/gallery/index.ejs
src/views/partials/view/image/header.ejs

- [ x ] Tests (`npm run test`) was run locally and all passed.
- [ x ] Lint (`npm run lint`) has passed locally and any fixes were made for failures
- image on embeds look better
- admin gallery go to the right image
- user gallery go to the right image

embed and views fixed more to be done 

---

server/routes/upload.js
server/tests/5-upload.spec.js

Issue Number: [SHARE-65](https://mrdemonwolf.atlassian.net/browse/SHARE-65)
-
-
-

[SHARE-65] Implement Upload Tests.

---

client/pages/account/devices/index.vue

Issue Number: [SHARE-70](https://mrdemonwolf.atlassian.net/browse/SHARE-70)
-
-
-

[SHARE-70] Changed error code.

---

server/routes/3rd-party/upload.js
server/routes/apiKey.js
server/tests/7-3rd-party.spec.js
server/utils/is-delete-key-valid.js

Issue Number: [SHARE-66](https://mrdemonwolf.atlassian.net/browse/SHARE-66)
-
-
-

[SHARE-66] Added 3rd-party tests.

---

docs/content/en/configuration.md
docs/content/en/mailtrap.md

Issue Number: [SHARE-103](https://mrdemonwolf.atlassian.net/browse/SHARE-103)
-
-
-

[SHARE-103] Added mailtrap and new env.

---

client/pages/dashboard/uploads/index.vue
client/pages/login/index.vue

Issue Number: [SHARE-110](https://mrdemonwolf.atlassian.net/browse/SHARE-110)
-
-
-

[SHARE-110] Implement manage upload copy link button
